### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Freundschaft** [ajcrowe/sentry-gitlab#8]
Internal Server Error
There was an internal server error while processing your request.

You may reference this error as 38b946e07a0a4d81a930b1fc33fdac0a.

Did I do something wrong? I configured the server, the API Key, the namespace, etc. How can I check what's going wrong? Thanks :)

**Comment by besir** [comment]
What's Your Sentry version?
My version is 7.6.0 and I have same problem.

In Internal errors I have this exeption:

Stacktrace (most recent call first):

  File "gitlab/__init__.py", line 126, in _raise_error_from_response
    response_body=response.content)
  File "gitlab/__init__.py", line 379, in get
    _raise_error_from_response(r, GitlabGetError)
  File "gitlab/__init__.py", line 737, in __init__
    data = self.gitlab.get(self.__class__, data, **kwargs)
  File "gitlab/__init__.py", line 680, in _get_list_or_object
    return cls(gl, id, **kwargs)
  File "gitlab/__init__.py", line 504, in Project
    return Project._get_list_or_object(self, id, **kwargs)
  File "sentry_gitlab/plugin.py", line 88, in create_issue
    proj = gl.Project(id=repo_url)
  File "sentry/plugins/bases/issue.py", line 170, in view
    request=request,
  File "sentry/plugins/base/v1.py", line 222, in get_view_response
    response = self.view(request, group)
  File "sentry/web/frontend/groups.py", line 540, in group_plugin_action
    response = plugin.get_view_response(request, group)
  File "sentry/web/decorators.py", line 182, in _wrapped
    return func(request, *args, **kwargs)
  File "sentry/web/decorators.py", line 236, in wrapped
    return func(request, *args, **kwargs)
  File "django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

**Comment by Freundschaft** [comment]
yes I'm using 7.6.0

**Comment by ajcrowe** [comment]
I'll try and look into this shortly. I've not upgraded my Sentry to `7.6`, we're running `7.5` so perhaps there is a new issue. Are you positive that it can access your Gitlab instance and the token is valid?

**Comment by Freundschaft** [comment]
yes, I have configured everything accordingly, if theres any way I can collect more logs I am happy to assist.

**Comment by besir** [comment]
@Freundschaft  try put project id to settings, no project namespace/name...
project id can find at the following command in terminal

curl --header "PRIVATE-TOKEN: xxxxxx" "http://gitlab.yourserver.com/api/v3/projects

Replace the xxxxxx with your reporter user private token. The token you find in "profile settings" > "Account"

Try this, for me is working.

@ajcrowe  This is not error in plugin, but change in gitlab. I have enhancement idea. If you call 
curl --header "PRIVATE-TOKEN: xxxxxx" "http://gitlab.yourserver.com/api/v3/projects
then you get list of projects in JSON. Can you add feature for listing project instead found and insert project id manualy...?

I have Gitlab 7.12.2 ;-)

**Comment by tbonz** [comment]
I'm using Hosted Sentry (8.4.0.dev0), and was having the same problem when trying to create an issue with GitLab (CE 8.6.1).  I was also getting an Internal Server Error on Sentry.  Using the GitLab project ID as suggested instead of the repository name worked for me.

**Comment by ajcrowe** [comment]
@besir that's a good idea, I've not got a lot of time at the mo. I'll add it as an enhancement idea.

@tbonz I will add something about the use of project ID rather than names and look at the new API

**Comment by ajcrowe** [comment]
Marking as closed, will create issues for the above
